(feat): added a support for running a scan using a repeater
NeuraLegion/incremental pull request #1
Opened 2024-02-14 14:34 UTC by DorShaer

Sometimes when running a scan a Repeater is needed.
I added a feature to include a Repeater ID when is specified and needed.

2024-02-14 14:46 UTC, bararchy requested changes

2024-02-14 14:46 UTC, bararchy commented on src/incremental.cr
> +      puts "Error when trying to start a scan: #{e}".colorize(:red)
Instead of all of those changes, I would just do something like: 

```
get(
        "/api/v1/scans",
        "POST",
        body: {
          tests:                tests,
          entryPointIds:        ep.map(&.id),
          attackParamLocations: locations,
          projectId:            @project_id,
          name:                 "Incremental Scan - #{Time.utc} - #{type}",
          repeaters:          @repeaters ? [@repeaters.to_s] : nil
        }.to_json
      )
```

2024-02-18 15:04 UTC, DorShaer commented
I added the changes required.
Please see the modified code

2024-02-18 15:04 UTC, DorShaer commented
I added the changes required.
Please see the modified code

2024-02-19 10:08 UTC, bararchy approved these changes

2024-02-19 10:08 UTC, merged